## First Version - configuration files in the configserver microservice, internal path
server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        #        native:
        #          search-locations: classpath:/configuration
        git:
          uri: https://github.com/JRoullet/kundapp_config.git
          username: JRoullet
          password: ${GIT_PASSWORD}
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true


#Will be used into docker-compose to pass the healthcheck step, configserver can now be pinged
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always