server:
  port: 8080
spring:
  web:
    locale: fr_FR
  thymeleaf:
    encoding: UTF-8
  application:
    name: "ms-webapp"
  config:
    import: configserver:http://msconfigserver:8888/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://msdiscovery:8761/eureka/

  endpoints:
    web:
      exposure:
        include: health, info, refresh