#server:
#  port: 8080
#spring:
#  application:
#    name: "ms-webapp"
#  datasource:
#    url: jdbc:mysql://msidentitydb:3306/identitydb
#    username: "root"
#    password: "root"
#  jpa:
#    show-sql: true
#  sql:
#    init:
#      mode: always
#
#  #------ Imported config must be quite empty to avoid loosing time from a/r -----#
##  Docker Configuration
#  config:
#    import: configserver:http://msconfigserver:8888/
#
##-----------EUREKA----------------
##--------------Eureka Server----------------
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://msdiscovery:8761/eureka/
#
##-----------Actuator----------------
##Will be used into docker-compose to pass the healthcheck step, service can now be pinged
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, refresh